name: Publish Extension

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: false
        default: 'current'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build extension
      run: npm run package
    
    - name: Create VSIX package
      run: npx @vscode/vsce package
    
    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-vsix
        path: '*.vsix'
    
    - name: Publish to VS Code Marketplace
      if: env.VSCE_TOKEN != ''
      run: |
        echo "🚀 Publishing to VS Code Marketplace..."
        npx @vscode/vsce publish --pat $VSCE_TOKEN
        echo "✅ Published to VS Code Marketplace"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
    
    - name: Publish to Open VSX Registry
      if: env.OVSX_TOKEN != ''
      run: |
        echo "🚀 Publishing to Open VSX Registry..."
        npx ovsx publish --pat $OVSX_TOKEN
        echo "✅ Published to Open VSX Registry"
      env:
        OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
    
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: '*.vsix'
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
