name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: npm
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lint
      run: npm run lint
    
    - name: Run type check
      run: npm run check-types
    
    - name: Compile
      run: npm run compile
    
    - name: Run tests on Linux
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    
    - name: Run tests on macOS/Windows
      run: npm test
      if: runner.os != 'Linux'
